x86: Use flags for capmode and simplify CGS addressing.
CTSRD-CHERI/cheri-specification pull request #11
Opened 2022-09-09 09:51 UTC by bsdjhb

This includes several changes:

- Use the flags field in the capability for CIP to define capability mode matching the approach used in CHERI-RISC-V rather than the D and B bits in the code and stack segment descriptors.  64-bit mode has already moved away from these bits for the most part, and Jess correctly noted that including the mode in the capability allows the encoding mode to be sealed.  This also means that flipping modes does not require far calls or jumps, just near absolute calls or jumps.

  While here, define capability mode in a standalone section rather than as part of the capability addressing mode.

  Add a subsection in the rationale section describing the old approach.

- Scrap the scheme to try to use segment prefixes to expand register selector fields for memory addressing.  Instead, use a more direct mapping where the FS and GS segment prefixes use the CFS and CGS registers as the base registers in capability addressing mode.

  The old scheme is described in a rationale subsection.

- Similarly, drop the hack to try to redefine the upper 3 bits of VEX and instead just say to use EVEX for CHERI instructions that want to use an additional capability register as an operand.

- The special MOV opcode for moves into/out of an additional capability register does not require a prefix.

- Drop quotes around capability mode to match the CHERI-RISC-V chapter.

- Don't suggest a control register (which can't be a cap) in the capability fault section.  Instead, suggest an additional (unnamed) control capability register.

- Define SWAPGS as a swap of CGS and KGS in capability mode.

- Add language around FS/GS aliases such as the *_BASE MSRs and {RD/WR}{FS/GS}BASE instructions.

2022-10-05 21:08 UTC, bsdjhb commented on chap-cheri-x86-64.tex
I guess so.  This dates back to when I leaning towards a different approach where the prefixes served as a 5th bit for selecting the base address.  In the current scheme sticking with a `cgs:` prefix probably does make sense.

2022-12-08 13:05 UTC, jonwoodruff requested changes
The most blatent issue is:
"The following changes are specific to **CHERI-RISC-V**:"
Maybe that should be fixed.

Otherwise, it looks like an improvement that we should be building upon.

2022-12-08 19:12 UTC, bsdjhb commented
> The most blatent issue is: "The following changes are specific to **CHERI-RISC-V**:" Maybe that should be fixed.
> 
> Otherwise, it looks like an improvement that we should be building upon.

Oops, yes, that should be fixed now.

2022-12-12 17:34 UTC, jonwoodruff approved these changes

2022-12-12 21:44 UTC, merged